apiVersion: v1
kind: Pod
metadata:
  name: fresco-nginx-pod
spec:
  containers:
   - name: fresco-nginx-containers
     image: nginx
     volumeMounts:
     - name: fresco
       mountPath: "/usr/share/nginx/html"     
     - name: fresco-secret
       mountPath: "/etc/test"
     env:
      - name: SERVER_URL_ENV
        valueFrom:
          configMapKeyRef:
            name: fresco-config
            key: SERVER_URL
  volumes:
  - name: fresco
    persistentVolumeClaim:
        claimName: fresco-pvc
  - name: fresco-secret
    secret:
      secretName: fresco-secret