apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: apm-server
    release: apm-server
  name: apm-server-apm-server
  namespace: default
spec:
  ports:
  - name: http
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: apm-server
    release: apm-server
  sessionAffinity: None
  type: ClusterIP
