apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
    labels:
      app: elasticsearch-master
      release: elasticsearch
    name: elasticsearch-master
    namespace: default
  spec:
    podManagementPolicy: Parallel
    replicas: 3
    selector:
      matchLabels:
        app: elasticsearch-master
    serviceName: elasticsearch-master-headless
    template:
      metadata:
        labels:
          app: elasticsearch-master
          chart: elasticsearch
          release: elasticsearch
        name: elasticsearch-master
      spec:
        containers:
        - env:
          - name: node.name
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: cluster.initial_master_nodes
            value: elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2,
          - name: discovery.seed_hosts
            value: elasticsearch-master-headless
          - name: cluster.name
            value: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-master
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        initContainers:
        - command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
          imagePullPolicy: IfNotPresent
          name: configure-sysctl
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
        terminationGracePeriodSeconds: 120

    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: elasticsearch-master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        volumeMode: Filesystem
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
