apiVersion: v1
kind: Service
metadata:
  annotations:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: kibana
    release: kibana
  name: kibana-kibana
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 30890
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
    release: kibana
  sessionAffinity: None
  type: LoadBalancer
